"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import logging
import re
from datetime import timedelta
from pathlib import Path
from urllib.parse import unquote, urlparse
import os
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

load_dotenv()
RAZORPAY_KEY_ID = os.getenv('RAZORPAY_KEY_ID')
RAZORPAY_KEY_SECRET = os.getenv('RAZORPAY_KEY_SECRET')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'unsafe-development-key-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
# V-02: fails CLOSED — an absent DJANGO_DEBUG means DEBUG=False, so an
# unconfigured deployment (forgotten env var) lands in the hardened
# configuration and must set a real DJANGO_SECRET_KEY to boot. Set
# DJANGO_DEBUG=true explicitly for local development only.
DEBUG = os.getenv('DJANGO_DEBUG', 'false').lower() == 'true'

ALLOWED_HOSTS = [host for host in os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if host]

if not DEBUG and not os.getenv('DJANGO_SECRET_KEY'):
    raise RuntimeError('DJANGO_SECRET_KEY must be set when DJANGO_DEBUG is false.')


def _env_bool(name, default):
    """Resolve an env-driven boolean, never crashing startup.

    Accepts the usual truthy spellings; anything else (or an absent var)
    falls back to the documented default instead of raising — the same
    fail-safe pattern as _env_int below.
    """
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().lower() in ('1', 'true', 'yes', 'on')



CSRF_COOKIE_SECURE = _env_bool('CSRF_COOKIE_SECURE', not DEBUG)


# Application definition

INSTALLED_APPS = [
    # SPEC-17-05 [R-17.9]: the MFAAdminConfig subclass swaps the default
    # admin site for one whose login form requires a TOTP code from
    # privileged roles — same app (label 'admin'), same registration flow,
    # one enforcement surface added at the admin door.
    'config.admin.MFAAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    # SPEC-17-01 [R-17.5/R-17.8/R-17.10]: token_blacklist provides the
    # OutstandingToken/BlacklistedToken tables behind refresh rotation,
    # secure logout, and session invalidation on critical account changes.
    'rest_framework_simplejwt.token_blacklist',
    'products',
    'cart',
    'orders',
    'accounts',
    'ops',
    'common',
    'corsheaders',
]

MIDDLEWARE = [
    # SPEC-20-3 [R-20.26]: per-request correlation id. First in the chain on
    # purpose, so the X-Request-ID header is on every response including the
    # ones produced above the view (security redirect, CORS preflight, admin
    # login bounce) and on the unhandled-exception 500.
    'common.middleware.RequestIDMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # SPEC-22-01: whitenoise serves STATIC_ROOT from the app process, so a
    # deployment with DEBUG=false still returns the admin CSS/JS. Placed
    # directly below SecurityMiddleware (its documented slot: after the
    # security headers, before anything that touches the request body or
    # the session) and unconditionally, so a misconfigured DEBUG cannot
    # silently drop assets.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # SPEC-9-03 (R-9.2.19, spec line 3002 "consistent error responses"):
    # every JSON error response is rewritten into the single uniform
    # {"error", "code", "details"} shape in one place — middleware-level,
    # because the ad-hoc {"error": ...} view returns raise no exception a
    # DRF EXCEPTION_HANDLER could see.
    'common.errors.ErrorEnvelopeMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases


def _query_options(query):
    """Return the DATABASES OPTIONS for a DATABASE_URL query string.

    libpq connection parameters travel in the URL query (a Heroku-style
    `postgres://...?sslmode=require`), and psycopg reads them from the
    connection OPTIONS dict. Dropping them (the pre-SPEC-22-01 behaviour)
    left a remote production database connecting unencrypted over whatever
    the network offered. Only bare `key=value` pairs are forwarded: a
    repeated key takes its last value (matching libpq, which takes the last
    occurrence) and a param with no `=` is ignored rather than guessed at.
    """
    if not query:
        return {}
    options = {}
    for pair in query.split('&'):
        if not pair or '=' not in pair:
            continue
        key, _, value = pair.partition('=')
        key = unquote(key).strip()
        if key:
            options[key] = unquote(value)
    return options


def _database_from_url(url):
    """Return a DATABASES['default'] entry for a DATABASE_URL, fail-safely.

    Parsed with stdlib urllib.parse rather than dj-database-url because that
    dependency (with psycopg) is deliberately deferred to the S22 deployment
    work, and the supported surface is only the two schemes this project
    needs. A missing, malformed, or unsupported URL falls back to the sqlite
    dev database instead of crashing startup — the same fail-safe pattern
    as _env_int below.
    """
    fallback = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
    if not url:
        return fallback
    try:
        parsed = urlparse(url)
        # Accessing .port validates it: a malformed port raises ValueError.
        port = parsed.port
    except ValueError:
        return fallback
    scheme = parsed.scheme.lower()
    if scheme in ('postgres', 'postgresql'):
        # The db name is never a filesystem path, so stripping all leading
        # slashes is safe here and accepts both /name and name forms.
        name = parsed.path.lstrip('/')
        if not name:
            return fallback
        config = {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': name,
        }
        if parsed.username:
            config['USER'] = unquote(parsed.username)
        if parsed.password is not None:
            config['PASSWORD'] = unquote(parsed.password)
        if parsed.hostname:
            config['HOST'] = parsed.hostname
        if port is not None:
            config['PORT'] = str(port)
        # SPEC-22-01: libpq connection params (sslmode above all) are part
        # of the URL, not noise — a remote production Postgres reached
        # without sslmode would carry its traffic in the clear.
        options = _query_options(parsed.query)
        if options:
            config['OPTIONS'] = options
        return config
    if scheme == 'sqlite':
        # Exactly one leading slash is stripped so that sqlite:///db.sqlite3
        # names a file relative to BASE_DIR while the four-slash form
        # (sqlite:////abs/path) and a drive prefix (sqlite:///C:/...) name
        # an absolute one. Path.isabs() is platform-dependent, so the
        # absolute check is done on the raw string instead.
        raw = parsed.path
        if raw.startswith('/'):
            raw = raw[1:]
        if not raw:
            return fallback
        name = Path(raw)
        is_absolute = raw.startswith('/') or (len(raw) > 1 and raw[1] == ':')
        return {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': name if is_absolute else BASE_DIR / name,
        }
    # Unsupported scheme (mysql://, ...): fall back rather than crash.
    return fallback


DATABASES = {'default': _database_from_url(os.getenv('DATABASE_URL'))}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

# SPEC-22-01: collectstatic needs a destination. Env-driven because the
# container image (Dockerfile) and a conventional VM/hosted deployment put
# it in different places; the default is the conventional in-backend
# directory so a deployment with no configuration at all still builds.
STATIC_ROOT = os.getenv('DJANGO_STATIC_ROOT') or str(BASE_DIR / 'staticfiles')

# whitenoise serves what collectstatic gathered, straight from the app
# process: no separate web server, no S3 bucket, no missing-asset 404s in
# production. USE_FINDERS follows DEBUG because without it a local dev
# server would 404 every asset until collectstatic was run by hand; in
# production (DEBUG=false) it is off and only STATIC_ROOT is consulted.
WHITENOISE_USE_FINDERS = DEBUG
WHITENOISE_AUTOREFRESH = DEBUG


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'true').lower() == 'true'
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3000').rstrip('/')
# SPEC-20-13: where the admin login page sends an account that MFA has
# blocked. Mandatory MFA (R-17.9) refuses an unenrolled privileged login,
# so without a reachable enrollment surface such an account is locked out
# of both /admin/ and the API with no way back in. The default is the
# storefront host's staff enrollment page, so a single-host deployment
# needs no extra configuration; override it only when the two live apart.
MFA_ENROLL_URL = os.getenv('MFA_ENROLL_URL', f"{FRONTEND_URL}/staff/mfa/enroll")
MEDIA_URL = '/media/'
# SPEC-2-04 [V-13]: uploads (product images, user files) are MEDIA, not
# STATIC. MEDIA_ROOT is env-driven for the same reason STATIC_ROOT is
# (SPEC-22-01): the container image mounts a persistent volume at
# /app/media and a host deployment puts it wherever its disk is, while
# local development keeps the conventional in-backend directory so the
# dev loop changes nothing.
MEDIA_ROOT = Path(os.getenv('DJANGO_MEDIA_ROOT') or (BASE_DIR / 'media'))

# An importable dotted path, nothing else: a filesystem path, a URL or a
# stray trailing dot can never be imported.
_DOTTED_PATH = re.compile(r'^[A-Za-z_]\w*(\.[A-Za-z_]\w*)+$')


def _env_dotted_path(name, default):
    """Resolve an importable dotted path (a storage backend) from the env.

    A malformed value is refused at boot rather than left to fail on the
    FIRST upload in production - the worst possible moment to discover the
    storage backend was never importable. Only the shape is checked here:
    a syntactically valid path to a backend that is not installed can only
    be caught by importing it, and importing an operator-supplied module at
    settings-import time is not something this project does.
    """
    raw = (os.getenv(name) or '').strip() or default
    if not _DOTTED_PATH.fullmatch(raw):
        raise ImproperlyConfigured(
            f'{name} must be an importable dotted Python path (the default is '
            f'{default}); got {raw!r}.'
        )
    return raw


# SPEC-2-04 [V-13]: STORAGES makes the media backend env-switchable, so a
# deployment can move uploads off the app filesystem with configuration
# alone - a mounted volume today (DJANGO_MEDIA_ROOT above), an object store
# later (DJANGO_MEDIA_BACKEND), with no code change and no storage-bucket
# model. Defaults are Django's own backends, so an unconfigured deployment
# behaves exactly as it did before.
#
# The staticfiles backend is deliberately left as StaticFilesStorage:
# whitenoise serves what collectstatic gathered from STATIC_ROOT, and a
# manifest-hashing storage would rewrite every collected asset URL.
MEDIA_BACKEND = _env_dotted_path(
    'DJANGO_MEDIA_BACKEND', 'django.core.files.storage.FileSystemStorage'
)
STORAGES = {
    'default': {'BACKEND': MEDIA_BACKEND},
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'
    },
}


def _env_int(name, default):
    # Env-driven ints must never take the app down at startup: a malformed
    # value falls back to the documented default instead of raising.
    try:
        return int(os.getenv(name, str(default)))
    except ValueError:
        return default


# Ops dashboard / /health/: a product with stock at or below this many units
# counts as "low stock". Tunable per deployment without a code change.
LOW_STOCK_THRESHOLD = _env_int('LOW_STOCK_THRESHOLD', 5)

# Ops dashboard: the "Sales over time" chart covers this many calendar days
# ending today. Tunable per deployment without a code change.
DASHBOARD_SALES_WINDOW_DAYS = _env_int('DASHBOARD_SALES_WINDOW_DAYS', 30)

# SPEC-20-8: "trust this device for N days" on the privileged MFA door. The
# TTL is the only knob: 30 days is the window the user directive asks for,
# and 0 is a safe kill switch that puts every privileged login straight back
# behind a fresh code, no code change needed. Trust is opt-in per device (no
# login can grant it), so this can only lengthen or shorten a grant the user
# already made — it cannot grant one.
MFA_TRUST_DAYS = _env_int('MFA_TRUST_DAYS', 30)
# The signed marker binding a trusted device to the browser that asked for
# it (HttpOnly, SameSite=Strict): a stolen password from any other browser
# still earns the challenge.
MFA_TRUST_COOKIE_NAME = os.getenv('MFA_TRUST_COOKIE_NAME', 'mfa_trusted_device')
MFA_TRUST_COOKIE_SAMESITE = os.getenv('MFA_TRUST_COOKIE_SAMESITE', 'Strict')

# SPEC-19-2 [R-19.20/R-19.21] admin alerts. Comma-separated staff/admin
# mailboxes; empty disables admin alerts entirely (no guessed recipient).
ALERT_RECIPIENTS = os.getenv('ALERT_RECIPIENTS', '')
# Per-alert-type dedupe window in seconds: an alert type that already sent
# inside the window is logged instead of re-sent (mail-bomb bound for the
# pollable /health/ and dashboard triggers).
ALERT_COOLDOWN_SECONDS = _env_int('ALERT_COOLDOWN_SECONDS', 300)
# "Payment-failure spike" rule (spec names the alert, not the number):
# at least this many failed payment attempts within a trailing window of
# this many seconds fires the spike alert (defaults: 3 in 300).
PAYMENT_FAILURE_SPIKE_COUNT = _env_int('PAYMENT_FAILURE_SPIKE_COUNT', 3)
PAYMENT_FAILURE_SPIKE_WINDOW_SECONDS = _env_int(
    'PAYMENT_FAILURE_SPIKE_WINDOW_SECONDS', 300
)

# Storefront products listing: rows per page. The historical hardcoded 2
# was a dev/test artifact (F-23); 12 is a storefront-appropriate default.
# Tunable per deployment without a code change; non-integer values are
# ignored and the default is used instead.
PRODUCTS_PAGE_SIZE = _env_int('PRODUCTS_PAGE_SIZE', 12)

# [R-21.2.6] Duplicate checkout submissions (double-click / client retry)
# collapse onto the still-payable pending order carrying the identical
# payload for this many seconds, instead of minting a second charge target.
# Tunable per deployment without a code change; non-integer values are
# ignored and the default is used instead.
CHECKOUT_DEDUP_WINDOW_SECONDS = _env_int('CHECKOUT_DEDUP_WINDOW_SECONDS', 300)

# SPEC-9-04 [R-9.2.14] Customer order-history listing (GET /api/orders/):
# rows per page, and the ceiling a ?page_size caller may request. The spec
# pins no number for order history, so both are deployment config
# (conventions.md: no hardcoded thresholds); non-integer values are ignored
# and the defaults are used instead.
ORDER_HISTORY_PAGE_SIZE = _env_int('ORDER_HISTORY_PAGE_SIZE', 10)
ORDER_HISTORY_MAX_PAGE_SIZE = _env_int('ORDER_HISTORY_MAX_PAGE_SIZE', 100)

# SPEC-12-01 [R-12.2] Inventory reservation: seconds a checkout's stock
# reservation holds units before it goes stale and becomes releasable by
# the reconciler (SPEC-12-03). Coordinate with the payment-provider session
# window: the customer must be able to finish paying inside the hold, so
# the default comfortably exceeds a typical Razorpay checkout session.
# Tunable per deployment without a code change; non-integer values are
# ignored and the default is used instead.
RESERVATION_TTL = _env_int('RESERVATION_TTL', 900)


# ISO 4217 currency codes are exactly three uppercase letters.
_ISO_4217 = re.compile(r"^[A-Z]{3}$")


def _env_currency(name, default):
    """Resolve an env-driven currency code, never crashing startup.

    A value that is not exactly three letters (ISO 4217 shape, upper-cased
    before matching) falls back to the documented default with a warning
    instead of failing the import — the same fail-safe pattern as _env_int
    and _env_log_level — so a typo in an env file cannot take the app down
    or mint orders in a currency the payment gateway would reject.
    """
    raw = os.getenv(name, "").strip().upper()
    if _ISO_4217.fullmatch(raw):
        return raw
    if raw:
        logging.getLogger(__name__).warning(
            "Ignoring unsupported %s value %r; using %s", name, raw, default
        )
    return default


# [R-8.11] Store currency for every money column (spec 8.3: "Store the
# currency alongside the amount"): new orders, order items, and their
# discount amounts are minted in this code, and the payment gateway is
# charged in it. Deliberately env-driven, not a SiteSettings column: a
# currency that changes would reprice historical rows' meaning, so it is
# never-changes-at-runtime config (the S16 boundary), not merchant-editable
# runtime state. Existing rows keep the currency they were minted with.
DEFAULT_CURRENCY = _env_currency('DEFAULT_CURRENCY', 'INR')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        # SPEC-17-03 [R-17.18]: CSRF gate for session-cookie mutations,
        # AFTER the JWT authenticator so bearer-authenticated requests
        # (checkout) short-circuit the chain and gain no CSRF friction —
        # an Authorization header cannot be attached cross-site. Every
        # request that does ride the session cookie (guest carts, session
        # logins) is CSRF-checked on unsafe methods; cart_detail's GET
        # issues the csrftoken cookie the SPA replays as X-CSRFToken.
        'common.authentication.SessionCartCSRFAuthentication',
    ),
    # Scoped throttling: every public mutating endpoint opts in by declaring
    # a `throttle_scope`; views without a scope are left unthrottled by this
    # class (conventions.md "Every public mutating endpoint gets a throttle
    # scope", V-04). Rates are deployment-tunable via environment variables.
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.ScopedRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'coupon': os.getenv('THROTTLE_COUPON_RATE', '10/min'),
        'cart': os.getenv('THROTTLE_CART_RATE', '60/min'),
        'auth': os.getenv('THROTTLE_AUTH_RATE', '10/min'),
        # Tighter than 'auth': the recovery views each send an email per
        # accepted request, so this budget is the outbound-mail-bomb bound.
        'recovery': os.getenv('THROTTLE_RECOVERY_RATE', '5/min'),
        # Payment intent minting (SPEC-11-01): every accepted request calls
        # the gateway and writes a payment event, so this budget bounds
        # both gateway spend and order-id brute-forcing.
        'payment': os.getenv('PAYMENT_THROTTLE_RATE', '10/min'),
        # SPEC-19-4 back-in-stock opt-in/opt-out: each opt-in is intent to
        # receive an outbound email, so the budget is the same shape as
        # the recovery bound (tighter than the generic auth budget).
        'restock': os.getenv('THROTTLE_RESTOCK_RATE', '5/min'),
    },
}

# SPEC-17-01 [R-17.5/R-17.8/R-17.10] JWT lifecycle: the access token is a
# short-lived bearer credential (15 minutes) carried by a rotating refresh
# token (7 days). ROTATE_REFRESH_TOKENS + BLACKLIST_AFTER_ROTATION mean
# every refresh mints a fresh refresh token and the presented one dies —
# a leaked refresh token cannot be replayed, and logout/password reset can
# revoke outstanding sessions through the blacklist tables. Lifetimes are
# env-driven integer seconds (documented in .env.example); non-integer
# values fall back to the documented defaults like every _env_int knob.
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(
        seconds=_env_int('JWT_ACCESS_TOKEN_LIFETIME_SECONDS', 900)
    ),
    'REFRESH_TOKEN_LIFETIME': timedelta(
        seconds=_env_int('JWT_REFRESH_TOKEN_LIFETIME_SECONDS', 604800)
    ),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# SPEC-17-02 [R-17.12]: the refresh token leaves the JSON body and browser
# localStorage entirely and rides an HttpOnly cookie (spec §17.1: "use
# secure, HttpOnly cookies ... Do not store long-lived authentication
# tokens in browser local storage"). Path is scoped to the API surface:
# accounts routes are mounted at both /api/accounts/ and /api/v1/account/,
# so /api/ covers both families while keeping the cookie off non-API paths.
# Secure follows DEBUG (V-02 fails closed); SameSite=Lax blocks cross-site
# attachment on POSTs (refresh/logout are POST-only) while matching the
# same-site deployment constraint BACKEND_REQUESTS.md already documents for
# the session cookie — strict CSRF enforcement for cookie-authenticated
# mutations is SPEC-17-03's follow-up.
JWT_REFRESH_COOKIE_NAME = os.getenv('JWT_REFRESH_COOKIE_NAME', 'refresh_token')
JWT_REFRESH_COOKIE_PATH = os.getenv('JWT_REFRESH_COOKIE_PATH', '/api/')
JWT_REFRESH_COOKIE_SAMESITE = os.getenv('JWT_REFRESH_COOKIE_SAMESITE', 'Lax')

# SPEC-17-03 [R-17.18]: the session cookie carries the cart identity, so
# its SameSite policy is explicit deployment config rather than an implicit
# Django default. Lax matches the JWT refresh cookie's reading (17-02):
# cross-site POSTs cannot attach it, while same-site navigation keeps the
# cart working. Server-side CSRF enforcement (SessionCartCSRFAuthentication
# above) is the actual gate — this is the same-site belt to its braces.
SESSION_COOKIE_SAMESITE = os.getenv('SESSION_COOKIE_SAMESITE', 'Lax')

CORS_ALLOWED_ORIGINS = [origin for origin in os.getenv(
    'CORS_ALLOWED_ORIGINS', 'http://localhost:3000'
).split(',') if origin]
CSRF_TRUSTED_ORIGINS = [origin for origin in os.getenv(
    'CSRF_TRUSTED_ORIGINS', 'http://localhost:3000'
).split(',') if origin]

CORS_ALLOW_CREDENTIALS = True

# SPEC-20-3 [R-20.26]: a browser may not read a cross-origin response header
# unless the server names it here, so without this the correlation id would
# be invisible to exactly the client that reports a failed request. The value
# is the literal header name (django-cors-headers joins these strings
# verbatim) and a test pins it to the middleware's constant, so the two
# cannot drift.
CORS_EXPOSE_HEADERS = ['X-Request-ID']


# Logging (SPEC-7-02): an env-driven dictConfig baseline. No external
# services are wired here — sentry/metrics/alerts stay deferred to the S22
# deployment work.

# The levels an operator may set via LOG_LEVEL. NOTSET is deliberately
# absent: a root logger at NOTSET logs everything, which is the opposite
# of a level constraint.
_VALID_LOG_LEVELS = ("DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL")


def _env_log_level(name, default):
    """Resolve an env-driven log level, never crashing startup.

    An unknown value falls back to the documented default with a warning
    instead of failing the import — the same fail-safe pattern as _env_int
    above — so a typo in an env file cannot take the app down.
    """
    raw = os.getenv(name, "").strip().upper()
    if raw in _VALID_LOG_LEVELS:
        return raw
    if raw:
        logging.getLogger(__name__).warning(
            "Ignoring unsupported %s value %r; using %s", name, raw, default
        )
    return default


def _build_logging(app_level, file_path=None):
    """Return the LOGGING dict for the given app level and optional file.

    Console is always wired (12-factor: logs stream to stdout and the
    platform decides where they go); a rotating file handler joins it only
    when LOG_FILE names a path, because no hardcoded path may assume a
    writable location — read-only filesystems and container stdout
    collection work with no configuration at all. django.request is pinned
    at ERROR and the audit-trail logger at INFO so request 5xx and the
    audit trail stay visible even when LOG_LEVEL is raised; neither adds
    handlers, so each record reaches the root handlers exactly once.
    """
    handlers = {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "plain",
        },
    }
    root_handlers = ["console"]
    if file_path:
        handlers["file"] = {
            "class": "logging.handlers.RotatingFileHandler",
            "formatter": "plain",
            "filename": file_path,
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 3,
        }
        root_handlers.append("file")
    return {
        "version": 1,
        # Loggers created before settings import (e.g. in dependencies)
        # keep working.
        "disable_existing_loggers": False,
        "formatters": {
            # Brace-style: audit detail payloads render dicts with braces,
            # which a %-style template would collide with on %% escaping.
            #
            # SPEC-20-3 [R-20.26]: the correlation id is stamped by the
            # formatter itself (one place, so a new call site cannot forget
            # it) rather than being added to each call site's format string.
            "plain": {
                "()": "common.middleware.RequestIDFormatter",
                "format": (
                    "{levelname} {asctime} {name} request_id={request_id} "
                    "{message}"
                ),
                "style": "{",
            },
        },
        "handlers": handlers,
        "root": {"handlers": root_handlers, "level": app_level},
        "loggers": {
            "django.request": {"level": "ERROR"},
            # The audit trail doubles as log output (SPEC-7-02): pinned at
            # INFO here so AuditEvent.record lines survive a raised
            # LOG_LEVEL.
            "common.audit": {"level": "INFO"},
        },
    }


APP_LOG_LEVEL = _env_log_level("LOG_LEVEL", "INFO")
LOGGING = _build_logging(APP_LOG_LEVEL, os.getenv("LOG_FILE"))


# SPEC-17-07 [R-17.11]: transport/cookie hardening flags, every one
# env-gated with safe-for-development defaults. The S22 deployment loop
# owns the production TLS topology; these flags only make the hardening
# REACHABLE from configuration, never on by default where it would break
# plain-HTTP local development (cookie-secure defaults do follow DEBUG, so
# an unconfigured DEBUG=false deployment lands in the hardened posture,
# consistent with the V-02 fail-closed reading of DEBUG).

# HSTS: seconds the browser must treat this host as HTTPS-only. 0 leaves
# the header unset entirely — the safe default, because enabling HSTS on a
# host that still serves plain HTTP locks real users out for the declared
# window. A production value (e.g. 31536000, with subdomains/preload only
# after the whole host tree is HTTPS) is S22's call.
SECURE_HSTS_SECONDS = _env_int('SECURE_HSTS_SECONDS', 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', False)
SECURE_HSTS_PRELOAD = _env_bool('SECURE_HSTS_PRELOAD', False)

# Redirect plain-HTTP requests to HTTPS. Off by default so local dev and
# the test suite (no TLS) keep working; enable behind a real deployment.
SECURE_SSL_REDIRECT = _env_bool('SECURE_SSL_REDIRECT', False)

# Behind a TLS-terminating reverse proxy Django only sees plain HTTP, so
# scheme-dependent behaviour (SSL redirect, cookie Secure flags, CSRF
# Referer checks) needs the proxy's forwarded-scheme header trusted
# explicitly. Both parts must be configured as a pair — a name without a
# value (or vice versa) is treated as unconfigured rather than trusted,
# mirroring the fail-safe fallbacks above. Never set this without the S22
# proxy actually sending the header: a forgeable pair lets a client lie
# about its scheme.
_proxy_header_name = os.getenv('SECURE_PROXY_SSL_HEADER_NAME', '')
_proxy_header_value = os.getenv('SECURE_PROXY_SSL_HEADER_VALUE', '')
SECURE_PROXY_SSL_HEADER = (
    (_proxy_header_name, _proxy_header_value)
    if _proxy_header_name and _proxy_header_value
    else None
)

# Session (cart identity / admin login) and CSRF cookies: Secure by
# default whenever DEBUG is off, mirroring the JWT refresh cookie's
# secure=not DEBUG contract in accounts/views.py — the three auth cookies
# can never disagree about transport security. The cart's csrftoken cookie
# (issued on GET /api/cart/) and CSRF_COOKIE_SECURE flip together, so SPA
# form posts keep working over HTTPS. Local development (DEBUG=true)
# stays off, and either default can be forced explicitly via env for
# exotic topologies.
SESSION_COOKIE_SECURE = _env_bool('SESSION_COOKIE_SECURE', not DEBUG)

# SPEC-17-08 [R-17.21]: product image upload size ceiling in whole MB.
# Enforced by products.validate_image_size on every upload surface (the
# API serializer field and the admin product form). A deployment raising
# it should also raise the web server's own body limit, which fires
# first and answers with its own 413.
MAX_UPLOAD_MB = _env_int('MAX_UPLOAD_MB', 5)
