"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import logging
import re
from pathlib import Path
from urllib.parse import unquote, urlparse
import os
from dotenv import load_dotenv

load_dotenv()
RAZORPAY_KEY_ID = os.getenv('RAZORPAY_KEY_ID')
RAZORPAY_KEY_SECRET = os.getenv('RAZORPAY_KEY_SECRET')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'unsafe-development-key-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'true').lower() == 'true'

ALLOWED_HOSTS = [host for host in os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if host]

if not DEBUG and not os.getenv('DJANGO_SECRET_KEY'):
    raise RuntimeError('DJANGO_SECRET_KEY must be set when DJANGO_DEBUG is false.')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'products',
    'cart',
    'orders',
    'accounts',
    'ops',
    'common',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # SPEC-9-03 (R-9.2.19, spec line 3002 "consistent error responses"):
    # every JSON error response is rewritten into the single uniform
    # {"error", "code", "details"} shape in one place — middleware-level,
    # because the ad-hoc {"error": ...} view returns raise no exception a
    # DRF EXCEPTION_HANDLER could see.
    'common.errors.ErrorEnvelopeMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases


def _database_from_url(url):
    """Return a DATABASES['default'] entry for a DATABASE_URL, fail-safely.

    Parsed with stdlib urllib.parse rather than dj-database-url because that
    dependency (with psycopg) is deliberately deferred to the S22 deployment
    work, and the supported surface is only the two schemes this project
    needs. A missing, malformed, or unsupported URL falls back to the sqlite
    dev database instead of crashing startup — the same fail-safe pattern
    as _env_int below.
    """
    fallback = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
    if not url:
        return fallback
    try:
        parsed = urlparse(url)
        # Accessing .port validates it: a malformed port raises ValueError.
        port = parsed.port
    except ValueError:
        return fallback
    scheme = parsed.scheme.lower()
    if scheme in ('postgres', 'postgresql'):
        # The db name is never a filesystem path, so stripping all leading
        # slashes is safe here and accepts both /name and name forms.
        name = parsed.path.lstrip('/')
        if not name:
            return fallback
        config = {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': name,
        }
        if parsed.username:
            config['USER'] = unquote(parsed.username)
        if parsed.password is not None:
            config['PASSWORD'] = unquote(parsed.password)
        if parsed.hostname:
            config['HOST'] = parsed.hostname
        if port is not None:
            config['PORT'] = str(port)
        # Extra query params (sslmode, ...) are deliberately ignored until
        # the S22 deployment work wires SSL options through.
        return config
    if scheme == 'sqlite':
        # Exactly one leading slash is stripped so that sqlite:///db.sqlite3
        # names a file relative to BASE_DIR while the four-slash form
        # (sqlite:////abs/path) and a drive prefix (sqlite:///C:/...) name
        # an absolute one. Path.isabs() is platform-dependent, so the
        # absolute check is done on the raw string instead.
        raw = parsed.path
        if raw.startswith('/'):
            raw = raw[1:]
        if not raw:
            return fallback
        name = Path(raw)
        is_absolute = raw.startswith('/') or (len(raw) > 1 and raw[1] == ':')
        return {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': name if is_absolute else BASE_DIR / name,
        }
    # Unsupported scheme (mysql://, ...): fall back rather than crash.
    return fallback


DATABASES = {'default': _database_from_url(os.getenv('DATABASE_URL'))}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'true').lower() == 'true'
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3000').rstrip('/')
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


def _env_int(name, default):
    # Env-driven ints must never take the app down at startup: a malformed
    # value falls back to the documented default instead of raising.
    try:
        return int(os.getenv(name, str(default)))
    except ValueError:
        return default


# Ops dashboard / /health/: a product with stock at or below this many units
# counts as "low stock". Tunable per deployment without a code change.
LOW_STOCK_THRESHOLD = _env_int('LOW_STOCK_THRESHOLD', 5)

# Ops dashboard: the "Sales over time" chart covers this many calendar days
# ending today. Tunable per deployment without a code change.
DASHBOARD_SALES_WINDOW_DAYS = _env_int('DASHBOARD_SALES_WINDOW_DAYS', 30)

# Storefront products listing: rows per page. The historical hardcoded 2
# was a dev/test artifact (F-23); 12 is a storefront-appropriate default.
# Tunable per deployment without a code change; non-integer values are
# ignored and the default is used instead.
PRODUCTS_PAGE_SIZE = _env_int('PRODUCTS_PAGE_SIZE', 12)

# [R-21.2.6] Duplicate checkout submissions (double-click / client retry)
# collapse onto the still-payable pending order carrying the identical
# payload for this many seconds, instead of minting a second charge target.
# Tunable per deployment without a code change; non-integer values are
# ignored and the default is used instead.
CHECKOUT_DEDUP_WINDOW_SECONDS = _env_int('CHECKOUT_DEDUP_WINDOW_SECONDS', 300)

# SPEC-9-04 [R-9.2.14] Customer order-history listing (GET /api/orders/):
# rows per page, and the ceiling a ?page_size caller may request. The spec
# pins no number for order history, so both are deployment config
# (conventions.md: no hardcoded thresholds); non-integer values are ignored
# and the defaults are used instead.
ORDER_HISTORY_PAGE_SIZE = _env_int('ORDER_HISTORY_PAGE_SIZE', 10)
ORDER_HISTORY_MAX_PAGE_SIZE = _env_int('ORDER_HISTORY_MAX_PAGE_SIZE', 100)


# ISO 4217 currency codes are exactly three uppercase letters.
_ISO_4217 = re.compile(r"^[A-Z]{3}$")


def _env_currency(name, default):
    """Resolve an env-driven currency code, never crashing startup.

    A value that is not exactly three letters (ISO 4217 shape, upper-cased
    before matching) falls back to the documented default with a warning
    instead of failing the import — the same fail-safe pattern as _env_int
    and _env_log_level — so a typo in an env file cannot take the app down
    or mint orders in a currency the payment gateway would reject.
    """
    raw = os.getenv(name, "").strip().upper()
    if _ISO_4217.fullmatch(raw):
        return raw
    if raw:
        logging.getLogger(__name__).warning(
            "Ignoring unsupported %s value %r; using %s", name, raw, default
        )
    return default


# [R-8.11] Store currency for every money column (spec 8.3: "Store the
# currency alongside the amount"): new orders, order items, and their
# discount amounts are minted in this code, and the payment gateway is
# charged in it. Deliberately env-driven, not a SiteSettings column: a
# currency that changes would reprice historical rows' meaning, so it is
# never-changes-at-runtime config (the S16 boundary), not merchant-editable
# runtime state. Existing rows keep the currency they were minted with.
DEFAULT_CURRENCY = _env_currency('DEFAULT_CURRENCY', 'INR')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Scoped throttling: every public mutating endpoint opts in by declaring
    # a `throttle_scope`; views without a scope are left unthrottled by this
    # class (conventions.md "Every public mutating endpoint gets a throttle
    # scope", V-04). Rates are deployment-tunable via environment variables.
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.ScopedRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'coupon': os.getenv('THROTTLE_COUPON_RATE', '10/min'),
        'cart': os.getenv('THROTTLE_CART_RATE', '60/min'),
        'auth': os.getenv('THROTTLE_AUTH_RATE', '10/min'),
        # Tighter than 'auth': the recovery views each send an email per
        # accepted request, so this budget is the outbound-mail-bomb bound.
        'recovery': os.getenv('THROTTLE_RECOVERY_RATE', '5/min'),
    },
}
CORS_ALLOWED_ORIGINS = [origin for origin in os.getenv(
    'CORS_ALLOWED_ORIGINS', 'http://localhost:3000'
).split(',') if origin]
CSRF_TRUSTED_ORIGINS = [origin for origin in os.getenv(
    'CSRF_TRUSTED_ORIGINS', 'http://localhost:3000'
).split(',') if origin]

CORS_ALLOW_CREDENTIALS = True


# Logging (SPEC-7-02): an env-driven dictConfig baseline. No external
# services are wired here — sentry/metrics/alerts stay deferred to the S22
# deployment work.

# The levels an operator may set via LOG_LEVEL. NOTSET is deliberately
# absent: a root logger at NOTSET logs everything, which is the opposite
# of a level constraint.
_VALID_LOG_LEVELS = ("DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL")


def _env_log_level(name, default):
    """Resolve an env-driven log level, never crashing startup.

    An unknown value falls back to the documented default with a warning
    instead of failing the import — the same fail-safe pattern as _env_int
    above — so a typo in an env file cannot take the app down.
    """
    raw = os.getenv(name, "").strip().upper()
    if raw in _VALID_LOG_LEVELS:
        return raw
    if raw:
        logging.getLogger(__name__).warning(
            "Ignoring unsupported %s value %r; using %s", name, raw, default
        )
    return default


def _build_logging(app_level, file_path=None):
    """Return the LOGGING dict for the given app level and optional file.

    Console is always wired (12-factor: logs stream to stdout and the
    platform decides where they go); a rotating file handler joins it only
    when LOG_FILE names a path, because no hardcoded path may assume a
    writable location — read-only filesystems and container stdout
    collection work with no configuration at all. django.request is pinned
    at ERROR and the audit-trail logger at INFO so request 5xx and the
    audit trail stay visible even when LOG_LEVEL is raised; neither adds
    handlers, so each record reaches the root handlers exactly once.
    """
    handlers = {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "plain",
        },
    }
    root_handlers = ["console"]
    if file_path:
        handlers["file"] = {
            "class": "logging.handlers.RotatingFileHandler",
            "formatter": "plain",
            "filename": file_path,
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 3,
        }
        root_handlers.append("file")
    return {
        "version": 1,
        # Loggers created before settings import (e.g. in dependencies)
        # keep working.
        "disable_existing_loggers": False,
        "formatters": {
            # Brace-style: audit detail payloads render dicts with braces,
            # which a %-style template would collide with on %% escaping.
            "plain": {
                "format": "{levelname} {asctime} {name} {message}",
                "style": "{",
            },
        },
        "handlers": handlers,
        "root": {"handlers": root_handlers, "level": app_level},
        "loggers": {
            "django.request": {"level": "ERROR"},
            # The audit trail doubles as log output (SPEC-7-02): pinned at
            # INFO here so AuditEvent.record lines survive a raised
            # LOG_LEVEL.
            "common.audit": {"level": "INFO"},
        },
    }


APP_LOG_LEVEL = _env_log_level("LOG_LEVEL", "INFO")
LOGGING = _build_logging(APP_LOG_LEVEL, os.getenv("LOG_FILE"))
