# Generated by Django 6.1.1 on 2026-09-20 06:19
# SPEC-8-01 [R-8.4]: Order.order_number backfill for pre-existing rows.

from django.db import migrations, models


def backfill_order_numbers(apps, schema_editor):
    """Assign ORD-YYYY-NNNNNN to every row that predates the field.

    Per-year sequence in id order, mirroring the runtime generator's
    semantics (created_at is stored UTC, the same clock the checkout-time
    generator reads), so historical numbers stay consistent with new ones.
    Single writer with a per-year counter inside one migration transaction,
    so the unique constraint cannot be violated by construction.
    """
    Order = apps.get_model('orders', 'Order')
    sequences = {}
    for order in Order.objects.order_by('id').iterator():
        year = order.created_at.year
        sequences[year] = sequences.get(year, 0) + 1
        order.order_number = f'ORD-{year}-{sequences[year]:06d}'
        order.save(update_fields=['order_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_razorpay_payment_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.RunPython(backfill_order_numbers, migrations.RunPython.noop),
    ]
