# Generated by Django 6.1.1 on 2026-09-20
# SPEC-8-02b [R-8.13]: OrderItem sku/variant_name snapshot columns + backfill.

from django.db import migrations, models


def backfill_order_item_snapshots(apps, schema_editor):
    """Populate the new snapshot columns for rows that predate the fields.

    Deterministic single pass in id order (same strategy class as 0006:
    id-ordered iteration over committed server-side state only -- no clock,
    no randomness, no external input, so the result is a pure function of
    the current database and every environment converges on the same rows).

    Population source mirrors checkout-time semantics: ``products`` has no
    product-level SKU, so ``sku`` stays empty; ``variant_name`` copies the
    product's CURRENT name where the product still exists (best-effort for
    legacy rows -- the at-purchase name already lives in ``product_name``).
    Rows whose product was deleted get empty snapshots: nothing honest is
    left to copy, and their ``product_name``/``price`` snapshots already
    carry the purchase record.
    """
    OrderItem = apps.get_model('orders', 'OrderItem')
    for item in OrderItem.objects.select_related('product').order_by('id').iterator():
        item.sku = ''
        item.variant_name = item.product.name if item.product_id else ''
        item.save(update_fields=['sku', 'variant_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sku',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.RunPython(backfill_order_item_snapshots, migrations.RunPython.noop),
    ]
