# Generated by Django 6.1.1 on 2026-09-20 08:16

import orders.models
from django.db import migrations, models


def backfill_currency_to_inr(apps, schema_editor):
    """[R-8.11] Deterministic backfill: every pre-existing money row was
    minted under the hardcoded-INR storefront, so all existing orders and
    items are stamped with the literal 'INR' — never with whatever
    DEFAULT_CURRENCY says in the environment running this migration (the
    fields' callable default would otherwise bake that environment's config
    into historical rows during AddField).
    """
    Order = apps.get_model('orders', 'Order')
    OrderItem = apps.get_model('orders', 'OrderItem')
    Order.objects.update(currency='INR')
    OrderItem.objects.update(currency='INR')


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_sku_orderitem_variant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(
                default=orders.models.default_currency, max_length=3
            ),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='currency',
            field=models.CharField(
                default=orders.models.default_currency, max_length=3
            ),
        ),
        # Reverse is a no-op: there is no pre-0008 currency state to restore
        # (dropping the columns is the undo, handled by unapplying above).
        migrations.RunPython(backfill_currency_to_inr, migrations.RunPython.noop),
    ]
