# Generated by Django 6.1.1 on 2026-10-01 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatusevent',
            name='trigger',
            field=models.CharField(choices=[('order_create', 'Order created'), ('admin_change_form', 'Admin change form'), ('admin_bulk_action', 'Admin bulk action'), ('payment_verify', 'Payment verified'), ('admin_api_fulfil', 'Admin fulfilment API'), ('admin_api_cancel', 'Admin cancel API'), ('payment_failed', 'Payment verification failed'), ('payment_webhook', 'Payment webhook')], max_length=30),
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('event_type', models.CharField(max_length=50)),
                ('gateway_payment_id', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payload', models.JSONField()),
                ('outcome', models.CharField(choices=[('applied', 'Applied'), ('refused', 'Refused'), ('recorded', 'Recorded')], default='recorded', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_events', to='orders.order')),
            ],
            options={
                'verbose_name': 'payment event',
                'verbose_name_plural': 'payment events',
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
