# Generated by Django 6.1.1 on 2026-10-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0018_order_shipping_amount_order_shipping_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_method_code",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
    ]
