# Generated by Django 6.1.1 on 2026-09-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_description_products_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
