# Generated by Django 6.1.1 on 2026-09-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productvariant'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['category'], name='products_category_idx'),
        ),
    ]
