# Generated by Django 6.1.1 on 2026-09-22 17:11

from django.db import migrations, models

import products.models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_stockreservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/",
                validators=[products.models.validate_image_size],
            ),
        ),
    ]
