# Generated by Django 6.1.1 on 2026-10-01 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="ShippingRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Region (state) this rate serves. Empty matches any region.",
                        max_length=100,
                    ),
                ),
                (
                    "postal_code_prefix",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Postal-code prefix this rate serves. Empty matches any code.",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="shipping.shippingmethod",
                    ),
                ),
            ],
            options={
                "ordering": ("amount", "pk"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("method", "region", "postal_code_prefix"),
                        name="shipping_rate_geography_uidx",
                    )
                ],
            },
        ),
    ]
