# Generated by Django 6.1.1 on 2026-09-18 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_sync_staff_role_groups'),
        ('orders', '0005_order_razorpay_payment_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('order', 'Order'), ('payment', 'Payment'), ('auth', 'Authentication')], db_index=True, max_length=20)),
                ('event_type', models.CharField(choices=[('order.created', 'Order created'), ('order.paid', 'Order paid'), ('payment.initiated', 'Payment intent created'), ('payment.signature_rejected', 'Payment signature rejected'), ('payment.order_not_found', 'Payment order not found'), ('payment.already_processed', 'Payment already processed'), ('payment.reference_mismatch', 'Payment reference mismatch'), ('payment.stock_conflict', 'Payment stock conflict'), ('payment.coupon_invalid', 'Payment coupon invalid'), ('payment.verified', 'Payment verified'), ('auth.registered', 'Account registered'), ('auth.login', 'Login succeeded'), ('auth.login_failed', 'Login failed'), ('auth.email_verified', 'Email verified'), ('auth.password_reset', 'Password reset')], db_index=True, max_length=50)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='orders.order')),
            ],
            options={
                'verbose_name': 'Audit event',
                'verbose_name_plural': 'Audit events',
                'ordering': ('-created_at',),
            },
        ),
    ]
