# Generated by Django 6.1.1 on 2026-09-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auditevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='request_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
