# Generated by Django 6.1.1 on 2026-09-30 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auditevent_source_alter_auditevent_category_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_admin_filters', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_admin_filters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved filter',
                'verbose_name_plural': 'Saved filters',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('user', 'content_type', 'name'), name='unique_saved_filter_per_user_model')],
            },
        ),
    ]
