# Generated by Django 6.1.1 on 2026-10-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0006_sync_staff_role_groups_superadmin"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationOutbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=50)),
                ("dedup_key", models.TextField(unique=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Notification outbox row",
                "verbose_name_plural": "Notification outbox rows",
                "ordering": ("created_at", "pk"),
            },
        ),
    ]
