# Generated by Django 6.1.1 on 2026-10-04 03:00

from django.db import migrations, models

import common.models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0007_notificationoutbox"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationoutbox",
            name="expires_at",
            field=models.DateTimeField(
                db_index=True, default=common.models.default_notification_outbox_expiry
            ),
        ),
    ]
