# Generated by Django 6.1.1 on 2026-10-06 07:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0008_notificationoutbox_expiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationoutbox",
            name="attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="notificationoutbox",
            name="last_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="notificationoutbox",
            name="next_attempt_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="notificationoutbox",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("dead", "Dead-lettered"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
            ),
        ),
    ]
