# Generated by Django 6.1.1 on 2026-10-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0009_notificationoutbox_attempts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("order.created", "Order created"),
                    ("order.paid", "Order paid"),
                    ("order.shipped", "Order shipped"),
                    ("order.delivered", "Order delivered"),
                    ("order.cancelled", "Order cancelled"),
                    ("payment.initiated", "Payment intent created"),
                    ("payment.signature_rejected", "Payment signature rejected"),
                    ("payment.order_not_found", "Payment order not found"),
                    ("payment.already_processed", "Payment already processed"),
                    ("payment.reference_mismatch", "Payment reference mismatch"),
                    ("payment.stock_conflict", "Payment stock conflict"),
                    ("payment.coupon_invalid", "Payment coupon invalid"),
                    ("payment.verified", "Payment verified"),
                    ("auth.registered", "Account registered"),
                    ("auth.login", "Login succeeded"),
                    ("auth.login_failed", "Login failed"),
                    ("auth.email_verified", "Email verified"),
                    ("auth.password_reset", "Password reset"),
                    ("catalogue.created", "Catalogue item created"),
                    ("catalogue.updated", "Catalogue item updated"),
                    ("catalogue.deleted", "Catalogue item deleted"),
                    ("staff.roles_updated", "Staff roles updated"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
