# Generated by Django 6.1.1 on 2026-10-02 08:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="return_window_days",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text="Days a customer has to request a return, counted from delivery where the goods have arrived and from the order date otherwise. Leave blank for the store default (30).",
                null=True,
                validators=[django.core.validators.MaxValueValidator(3650)],
            ),
        ),
    ]
